{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"EBird Data Nadia District\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.123.742.0 (23.11)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "76d2e800-d223-4140-9c89-ba8b3e80b00f",
        "fromColumn": "OBSERVATION DATE",
        "fromTable": "EBird Data Nadia District",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_d9d9e745-576c-481e-97cd-71fc8279c814"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "EBird Data Nadia District",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "COMMON NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2e40e21-b88b-4ad3-8b29-3b1b07604f0c",
            "sourceColumn": "COMMON NAME",
            "summarizeBy": "none"
          },
          {
            "name": "OBSERVATION COUNT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2912e8b2-6394-491c-ae3c-2c9521b2b3cc",
            "sourceColumn": "OBSERVATION COUNT",
            "summarizeBy": "none"
          },
          {
            "name": "LOCALITY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c3f08259-ffd8-4301-b04d-4e060c0f3390",
            "sourceColumn": "LOCALITY",
            "summarizeBy": "none"
          },
          {
            "name": "LATITUDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f1e11808-1848-41a6-ba3e-4bf77ea81449",
            "sourceColumn": "LATITUDE",
            "summarizeBy": "sum"
          },
          {
            "name": "LONGITUDE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6b0adb14-d951-4788-84aa-757d8bc3ff7f",
            "sourceColumn": "LONGITUDE",
            "summarizeBy": "sum"
          },
          {
            "name": "OBSERVATION DATE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5a4e9a21-7e4c-47ef-84dd-e746d4b8418c",
            "sourceColumn": "OBSERVATION DATE",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_d9d9e745-576c-481e-97cd-71fc8279c814"
                },
                "isDefault": true,
                "relationship": "76d2e800-d223-4140-9c89-ba8b3e80b00f"
              }
            ]
          },
          {
            "name": "PROTOCOL TYPE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f405c9df-3035-4f07-b1ee-e8d5b387dcb5",
            "sourceColumn": "PROTOCOL TYPE",
            "summarizeBy": "none"
          },
          {
            "name": "DURATION MINUTES",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3f27effe-ee7e-43f2-ad4e-d06917d224c6",
            "sourceColumn": "DURATION MINUTES",
            "summarizeBy": "sum"
          },
          {
            "name": "EFFORT DISTANCE KM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "83407a7c-530a-4d48-8b11-1f0107c37245",
            "sourceColumn": "EFFORT DISTANCE KM",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "d1fd6ad3-17e8-48a0-97c6-c56bed9f85fc",
        "partitions": [
          {
            "name": "EBird Data Nadia District",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\arghy\\Downloads\\EBird Data Nadia District.xlsx\"), null, true),",
                "    #\"EBird Data Nadia District_Sheet\" = Source{[Item=\"EBird Data Nadia District\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"EBird Data Nadia District_Sheet\", [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"COMMON NAME\", type text}, {\"OBSERVATION COUNT\", type text}, {\"LOCALITY\", type text}, {\"LATITUDE\", type number}, {\"LONGITUDE\", type number}, {\"OBSERVATION DATE\", type date}, {\"PROTOCOL TYPE\", type text}, {\"DURATION MINUTES\", Int64.Type}, {\"EFFORT DISTANCE KM\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_c8f0a409-2524-4a7d-a14e-4d5c37cc2416",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e251b5da-088a-4ee8-964d-d9f9f37dbaef",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4be2364c-7dc0-4c50-ace9-e6c67876743b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "22391458-e0c9-485e-bdf6-3440146de734",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "562a0848-fad2-4ac9-9ca2-8075876deacd",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2b92bf0a-03b2-455b-baa3-894284cbf25e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "4879541a-bd26-4df2-924e-41d3dc4f3f65",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "57d2e2e4-61c6-474f-8120-8b4d9f9ecec9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "175fe6d2-5b98-44c9-aa94-5022139aa3f7",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "fda1181b-5f56-4f03-9fc7-159232605923",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "60c43b3e-da96-4e02-a851-4dfb86aee24f",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "4de46e3e-c490-40a6-8f8e-29331ce077f2",
                "ordinal": 3
              }
            ],
            "lineageTag": "98e5aea8-2a98-4c8b-826d-8967ba34d944"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "56d055fb-5861-429e-9373-258cda08b3d4",
        "partitions": [
          {
            "name": "DateTableTemplate_c8f0a409-2524-4a7d-a14e-4d5c37cc2416",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_d9d9e745-576c-481e-97cd-71fc8279c814",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "44e8cacf-fad0-4f2d-be99-26043df8731c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ff321d14-7f75-480a-bcea-14b6e2153f25",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "12472913-83ee-4ec3-b0a9-f8b512ad8a32",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "11cb703b-4e7e-4395-84e2-049afa2fdeae",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "df0dc63c-7426-45cd-a2f3-079db31c93e5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "2a24420d-73e8-4d1f-8fbb-ed5e20044dc8",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7c3db262-6c0e-4bcc-8ef1-5f41e5405606",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "aa3ebdbd-de85-4255-b73a-90687f8c9502",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "209d4580-ee4e-43ec-8c1b-dbbe50c8d30b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "625f5d5b-5e67-4deb-b816-281a6cf1e627",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e94e304a-fcf8-44ff-9326-ac4b7f471787",
                "ordinal": 3
              }
            ],
            "lineageTag": "1b2b886e-6c33-4dfe-b5ff-0ce8cd58478c"
          }
        ],
        "isHidden": true,
        "lineageTag": "cdb79afb-8003-40b2-963a-8a43301aced7",
        "partitions": [
          {
            "name": "LocalDateTable_d9d9e745-576c-481e-97cd-71fc8279c814",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('EBird Data Nadia District'[OBSERVATION DATE])), 1, 1), Date(Year(MAX('EBird Data Nadia District'[OBSERVATION DATE])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}